apiVersion: v1
kind: Service
metadata:
  name: kubernetes-jenkins-astrovilla-app
spec:
  selector:
    app: kubernetes-jenkins-astrovilla
  type: NodePort
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 80
    nodePort: 32110
