apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-kuber-deploymentee
  labels:
    app: astro-kuberer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-kuberer
  template:
    metadata:
      labels:
        app: astro-kuberer
    spec:
      containers:
      - name: astro-kuberer
        image: nagasatishdocker/astrovilla-kubernetes
        ports:
        - containerPort: 80
