apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-jenkins-astrovilla-app
  labels:
    app: kubernetes-jenkins-astrovilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-jenkins-astrovilla
  template:
    metadata:
      labels:
        app: kubernetes-jenkins-astrovilla
    spec:
      containers:
      - name: kubernetes-jenkins-astrovilla
        image: nagasatishdocker/kubernetes-jenkins-astrovilla
        ports:
        - containerPort: 80
