apiVersion: v1
kind: Service
metadata:
  name: astro-kuber-service
spec:
  selector:
    app: astro-kuber
  type: NodePort
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 80
    nodePort: 32110
